
version : 0.2

phases:
    build:
      commands:
         - echo Build started on 'date'
         - mvn clean compile package
         
    post_build:
     commands:  
         -echo Build completed on 'date'
         
artifacts:
 files:
    -target/test.jar
    
 discard-paths: yes
       